var fs = require('fs');
var vhost = require('vhost');
var express = require('express');
var http = require('http');
var https = require('https');
var privateKey  = fs.readFileSync('/home/gdbix/certs/arabiancha.in.key', 'utf8');
var certificate = fs.readFileSync('/home/gdbix/certs/arabiancha.in.cert', 'utf8');
var credentials = {key: privateKey, cert: certificate};
var app = express();
app.use(vhost('rpc.arabiancha.in', require('./index.js').app));
var httpServer = http.createServer(app);
var httpsServer = https.createServer(credentials, app);
httpServer.listen(80);
httpsServer.listen(443);
